# Generated by Django 5.0.1 on 2024-02-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0002_alter_pay_image_alter_shop_logo_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(upload_to='shop_logo/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='user/%Y/%m'),
        ),
    ]
