# Generated by Django 5.0.1 on 2024-01-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0004_pay_shop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eCommerceApp.pay'),
        ),
    ]
