# Generated by Django 5.0.1 on 2024-01-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0005_order_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_fee',
        ),
    ]
